package_assets: on
package_path: assets-compiled
compress_assets: true
javascript_compressor: closure
gzip_assets: true
embed_assets: on

javascripts:
  application:
    - public/components/jquery/jquery.js
    - public/javascripts/application.js

stylesheets:
  application:
    - public/stylesheets/**/*.css
